doctrine_migrations:
    services:
        'Doctrine\Migrations\Version\MigrationFactory': 'App\Migrations\Factory\MigrationFactoryDecorator'

    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

    enable_profiler: '%kernel.debug%'