fervo_enum:
  enums:
    App\Entity\ApplicationScope:
      doctrine_type: application_scope
      form_type: application_scope
    App\Entity\ActiveDirectorySyncSourceType:
      doctrine_type: ad_source_type
      form_type: ad_source_type
    App\Entity\ServiceAttributeType:
      doctrine_type: service_attribute_type
      form_type: service_attribute_type
