parameters:
    idp_cert_file: "%kernel.project_dir%/certs/idp.crt"
    idp_cert_key: "%kernel.project_dir%/certs/idp.key"


light_saml_symfony_bridge:
  own:
      entity_id: "%env(SAML_ENTITY_ID)%"
      credentials:
          -
              certificate: "%idp_cert_file%"
              key: "%idp_cert_key%"
              password:    ~
  system:
      event_dispatcher: ~
      logger: ~
  store:
      request: ~
      id_state: ~
      sso_state: ~