framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            provision: "%env(MESSENGER_TRANSPORT_DSN)%?queue_name=provision"

        routing:
            'App\Message\MustProvisionUser': provision
