nelmio_api_doc:
    documentation:
        info:
            title: '%env(APP_NAME)%'
            description: ~
            version: '%version%'
        components:
            securitySchemes:
                apiKey:
                    type: apiKey
                    name: X-Token
                    in: header
        security:
            - apiKey: [ ]

    areas:
        ad_connect:
            path_patterns:
                - ^/api/ad_connect
        idp_exchange:
            path_patterns:
                - ^/api/idp_exchange
        default:
            path_patterns:
                - ^/api