nelmio_api_doc:
    documentation:
        info:
            title: '%env(APP_NAME)%'
            description: ~
            version: '%version%'
        securityDefinitions:
            apiKey:
                type: apiKey
                name: X-Token
                in: header
        security:
            - apiKey: [ ]
    areas:
        ad_connect:
            path_patterns: [ ^/api/ad_connect ]

        default:
            path_patterns: [ ^/api/(?!ad_connect) ]