nelmio_api_doc:
    documentation:
        info:
            title: '%app_name%'
            description: ~
            version: '%version%'
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc.json$) # Accepts routes under /api except /api/doc
