security:
    encoders:
        App\Entity\User:
          algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database:
            entity:
                class: App:User
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER,
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_decision_manager:
        strategy: unanimous

    access_control:
        - { path: ^/exchange, roles: ROLE_IDPEXCHANGE }
        - { path: ^/api/ad_connect, roles: ROLE_ADCONNECT }
        - { path: ^/api, roles: ROLE_API }
        - { path: ^/docs/api, roles: ROLE_SUPER_ADMIN }
        - { path: ^/users, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/login/two_factor, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/logout, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        metadata:
            pattern: ^/metadata$
            security: false

        composer:
            anonymous: ~
            pattern: ^/dependencies

        exchange:
            pattern: ^/exchange
            stateless: true
            guard:
                authenticators:
                    - App\Security\ApplicationAuthenticator

        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - App\Security\ApplicationAuthenticator

        login:
            anonymous: ~
            pattern: ^/login$

        register:
            anonymous: ~
            pattern: ^/register

        forgot_password:
            anonymous: ~
            pattern: ^/forgot_pw

        secured:
            pattern: ^/
            user_checker: App\Security\UserChecker
            logout:
                path: /logout
                target: /login
                invalidate_session: true
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                csrf_token_generator: security.csrf.token_manager
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                token_provider: Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider
            provider: database

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
