parameters:
    locale: 'de'
    locales: [ 'de', 'en' ]

framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
