twig:
    paths:
      '%kernel.project_dir%/templates': ~
      '%kernel.project_dir%/public/build': build
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null

    form_themes:
      - form/layout.html.twig
    globals:
      config: '@SchulIT\CommonBundle\Twig\ConfigVariable'
      user: '@App\Twig\UserVariable'
      profile_url: "profile"
      health_check: '@App\HealthCheck\HealthCheckService'
      helpdesk_mail: '%env(HELPDESK_MAIL)%'
      login_help: '%env(LOGIN_HELP)%'
