scheb_two_factor:

    # Trusted computer feature
    trusted_device:
        enabled: true                  # If the trusted computer feature should be enabled
        cookie_name: trusted_device    # Name of the trusted computer cookie
        lifetime: 5184000       # Lifetime of the trusted computer cookie
        cookie_secure: true     # Set the 'Secure' (HTTPS Only) flag on the trusted_computer cookie
        cookie_same_site: "strict"     # The same-site option of the cookie, can be "lax" or "strict"

    # Email authentication config
    email:
        enabled: false                  # If email authentication should be enabled, default false

    # Google Authenticator config
    google:
        enabled: true                  # If Google Authenticator should be enabled, default false
#        server_name: '%app_host%'      # Server name used in QR code
        issuer: '%env(APP_NAME)%'           # Issuer name used in QR code
        template: 'auth/two_factor_google.html.twig'   # Template used to render the authentication form

    backup_codes:
        enabled: true

    # The service which is used to persist data in the user object. By default Doctrine is used. If your entity is
    # managed by something else (e.g. an API), you have to implement a custom persister
    persister: scheb_two_factor.persister.doctrine

    # If your Doctrine user object is managed by a model manager, which is not the default one, you have to
    # set this option. Name of entity manager or null, which uses the default one.
    model_manager_name: ~

    # The security token classes, which trigger two-factor authentication.
    # By default the bundle only reacts to Symfony's username+password authentication. If you want to enable
    # two-factor authentication for other authentication methods, add their security token classes.
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken

    # A list of IP addresses, which will not trigger two-factor authentication
    #ip_whitelist:
    #    - 127.0.0.1