#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
  path: /login/check

2fa_login:
  path: /login/two_factor
  defaults:
    _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
  path: /login/two_factor/check

common:
    resource: "@CommonBundle/Controller"
    type: annotation

logout:
  path: /logout

app.swagger_ui:
  path: /docs/api
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

r_u2f:
  defaults: { _controller: R\U2FTwoFactorBundle\Controller\RegisterController::u2fAction }
  path: /two_factor/u2f/u2f_register

composer:
    resource: '@ComposerDependencyListBundle/Controller'
    type: annotation
    prefix: /dependencies