#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
  path: /login/check

2fa_login:
  path: /login/2fa
  defaults:
    # "scheb_two_factor.form_controller" references the controller service provided by the bundle.
    # You don't HAVE to use it, but - except you have very special requirements - it is recommended.
    _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
  path: /login/2fa/check

common:
    resource: "@CommonBundle/Controller"
    type: annotation

logout:
  path: /logout

app.swagger_ui:
  path: /docs/api
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }

app.swagger_ui.ad_connect:
  path: /docs/api/ad_connect
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: ad_connect }

composer:
    resource: '@ComposerDependencyListBundle/Controller'
    type: annotation
    prefix: /dependencies