services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

    App\Repository\UserRepositoryInterface:
        class: App\Repository\UserRepository
        arguments:
            - "@doctrine.orm.default_entity_manager"
        public: true