name: Dokumentation

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Dokumentation erstellen
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change Directory
        run: cd docs

      - name: Build
        run: npm run build

      - name: Copy to server
        run: rsync --delete -rvzh ./build/ github@srv2.mmarnitz.de:/srv/http/docs.schulit.de/idp